import { useEffect, useMemo, useRef, useState } from 'react';
import type React from 'react';
import { Sidebar, Header, Card, Icons } from './components';
import { initialAssets, initialHistory, ownerAmount, ownerPrevious, pct, yen } from './data';
import type { Asset, Category, HistoryRecord, Owner, Page } from './types';
import type { CashflowItem } from './types';
import { AssetCategoryView, CategoryAssetForm, IncomeView } from './extraViews';

const categoryColors: Record<Category, string> = { '預金': '#35d6ba', '国内株式': '#6ba5ff', '米国株式': '#2bbef2', '暗号資産': '#f8ad4d', '投資信託': '#c36eff', 'その他':'#94a3b8' };

function AnimatedYen({value}:{value:number}){
  const previous=useRef(value); const [display,setDisplay]=useState(value);
  useEffect(()=>{const from=previous.current,to=value,start=performance.now(),duration=650;let frame=0;const tick=(now:number)=>{const p=Math.min((now-start)/duration,1),ease=1-Math.pow(1-p,3);setDisplay(from+(to-from)*ease);if(p<1)frame=requestAnimationFrame(tick);else previous.current=to};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);
  return <>{yen(display)}</>;
}

function LineChart({records,scope}:{records:HistoryRecord[];scope:'世帯全体'|'夫'|'妻'}) {
  const values = records.map(m => scope==='世帯全体'?m.husband+m.wife:scope==='夫'?m.husband:m.wife); const min = Math.min(...values); const max = Math.max(...values);
  const range=max-min||1,step=values.length>1?91/(values.length-1):0;const y=(v:number)=>78-((v-min)/range)*55;const pts=values.map((v,i)=>({x:8+i*step,y:y(v)}));
  const curve=pts.length?pts.slice(1).reduce((d,p,i)=>{const prev=pts[i],mx=(prev.x+p.x)/2;return `${d} C ${mx},${prev.y} ${mx},${p.y} ${p.x},${p.y}`},`M ${pts[0].x},${pts[0].y}`):'';
  const area=`${curve} L ${pts[pts.length-1]?.x??99},85 L ${pts[0]?.x??8},85 Z`;
  const focusIndex=Math.max(0,pts.length-3),focus=pts[focusIndex],focusRecord=records[focusIndex],focusValue=values[focusIndex]??0;
  return <div className="chart-wrap">{focus&&<div className="chart-tooltip" style={{left:`${focus.x/1.07}%`}}><small>{focusRecord?.month.replace('-','/')}</small><b>{yen(focusValue)}</b></div>}<svg viewBox="0 0 107 88" preserveAspectRatio="none" className="line-chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1fe4d1" stopOpacity=".34"/><stop offset=".7" stopColor="#0db5a7" stopOpacity=".1"/><stop offset="1" stopColor="#07131e" stopOpacity="0"/></linearGradient><filter id="lineGlow"><feGaussianBlur stdDeviation="1.6" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{focus&&<line className="chart-guide" x1={focus.x} x2={focus.x} y1="12" y2="82"/>}<path className="chart-area" d={area} fill="url(#area)"/><path className="chart-glow-line" d={curve} fill="none" stroke="#31f2df" strokeWidth="1.65" vectorEffect="non-scaling-stroke" filter="url(#lineGlow)"/>{pts.map((p,i)=><circle className={i===focusIndex?'focus-point':''} key={i} cx={p.x} cy={p.y} r={i===focusIndex?'1.45':'.72'} fill="#bafff7" stroke="#1fe4d1" strokeWidth=".6" vectorEffect="non-scaling-stroke"/>)}</svg><div className="chart-labels">{records.map(m=><span key={m.month}>{Number(m.month.slice(5))}月</span>)}</div></div>;
}

function Dashboard({ assets, records, add, showAssets }: { assets: Asset[]; records:HistoryRecord[]; add: () => void; showAssets:()=>void }) {
  const [scope,setScope]=useState<'世帯全体'|'夫'|'妻'>('世帯全体');
  const [period,setPeriod]=useState<'1ヶ月'|'3ヶ月'|'6ヶ月'|'1年'|'全期間'>('1年');
  const years=[...new Set(records.map(r=>r.month.slice(0,4)))].sort((a,b)=>b.localeCompare(a)); const [year,setYear]=useState(years[0]||'2026'); const yearRecords=records.filter(r=>r.month.startsWith(year)).sort((a,b)=>a.month.localeCompare(b.month));
  const periodCount={'1ヶ月':2,'3ヶ月':3,'6ヶ月':6,'1年':12,'全期間':records.length}[period];const chartRecords=(period==='全期間'?[...records].sort((a,b)=>a.month.localeCompare(b.month)):yearRecords).slice(-periodCount);
  const householdTotal=assets.reduce((s,a)=>s+a.amount,0), husbandTotal=assets.reduce((s,a)=>s+ownerAmount(a,'夫'),0), wifeTotal=assets.reduce((s,a)=>s+ownerAmount(a,'妻'),0);
  const amountFor=(a:Asset)=>scope==='世帯全体'?a.amount:ownerAmount(a,scope);
  const previousFor=(a:Asset)=>scope==='世帯全体'?a.previous:ownerPrevious(a,scope);
  const total=assets.reduce((s,a)=>s+amountFor(a),0), previous=assets.reduce((s,a)=>s+previousFor(a),0);
  const groups=Object.entries(assets.reduce<Record<string,number>>((r,a)=>({...r,[a.category]:(r[a.category]||0)+amountFor(a)}),{})).filter(([,v])=>v>0);
  let offset = 0; const stops = groups.map(([c,v]) => { const start=offset; offset += v/total*100; return `${categoryColors[c as Category]} ${start}% ${offset}%`; }).join(',');
  const changeYear=(direction:number)=>{const i=years.indexOf(year),next=years[i-direction];if(next)setYear(next)};
  return <><Header title="ダッシュボード" subtitle="夫婦と世帯全体の資産状況を確認できます"/>
    <div className="dashboard-year-picker"><Icons.CalendarDays/><button onClick={()=>changeYear(-1)}><Icons.ChevronLeft/></button><select value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y} value={y}>{y}年</option>)}</select><button onClick={()=>changeYear(1)}><Icons.ChevronRight/></button></div>
    <div className="scope-tabs">{(['世帯全体','夫','妻'] as const).map(s=><button key={s} className={scope===s?'active':''} onClick={()=>setScope(s)}>{s}</button>)}</div>
    <div className="couple-summary"><div><span>世帯総資産</span><b><AnimatedYen value={householdTotal}/></b><small className="summary-change">前月比　<span>+{yen(householdTotal-assets.reduce((s,a)=>s+a.previous,0))}</span></small><svg className="summary-spark" viewBox="0 0 120 45"><path d="M2 40 C20 36,22 31,38 32 S56 26,70 28 S91 18,118 4"/></svg></div><div><span className="summary-owner husband"><i><Icons.UserRound/></i><strong>夫</strong></span><b><AnimatedYen value={husbandTotal}/></b><small>構成比　{(husbandTotal/householdTotal*100).toFixed(1)}%</small><i className="summary-progress husband-progress" style={{'--fill':`${husbandTotal/householdTotal*100}%`} as React.CSSProperties}/></div><div><span className="summary-owner wife"><i><Icons.UserRound/></i><strong>妻</strong></span><b><AnimatedYen value={wifeTotal}/></b><small>構成比　{(wifeTotal/householdTotal*100).toFixed(1)}%</small><i className="summary-progress wife-progress" style={{'--fill':`${wifeTotal/householdTotal*100}%`} as React.CSSProperties}/></div></div>
    <Card className="hero"><div><span className="eyebrow">{scope}の資産額</span><div className="total"><AnimatedYen value={total}/></div><div className="gain"><Icons.ArrowUpRight size={15}/>{yen(total-previous)}（{pct(total,previous)}）<small>前月比</small></div></div><div className="as-of"><span>表示対象</span><b>{scope}</b></div></Card>
    <div className="dashboard-grid"><Card><div className="card-title"><div><h2>ポートフォリオ配分</h2><p>カテゴリ別の資産割合</p></div></div><div className="allocation"><div className="donut" style={{background:`conic-gradient(${stops})`}}><div><span>合計</span><b>{yen(total)}</b></div></div><div className="legend allocation-list">{groups.map(([c,v])=><div key={c}><i style={{background:categoryColors[c as Category]}}/><span>{c}<small>{yen(v)}</small></span><b>{(v/total*100).toFixed(1)}%</b></div>)}</div></div><button className="allocation-detail" onClick={showAssets}>詳細を見る <Icons.ChevronRight/></button></Card>
      <Card><div className="card-title"><div><h2>資産推移</h2><p>{scope}・{period==='全期間'?'全期間':year+'年'}の推移</p></div><div className="period-tabs">{(['1ヶ月','3ヶ月','6ヶ月','1年','全期間'] as const).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div>{chartRecords.length>1?<LineChart records={chartRecords} scope={scope}/>:<div className="empty-chart">この期間のデータが不足しています</div>}</Card></div>
    <Card className="dashboard-assets"><div className="card-title"><div><h2>主な資産</h2><p>評価額上位の資産</p></div><button className="text-button">すべての資産を見る</button></div><div className="dash-table"><div className="dash-row dash-head"><span>資産クラス</span><span>資産名称</span><span>保有者</span><span>評価額</span><span>構成比</span><span>前月比</span></div>{[...assets].filter(a=>amountFor(a)>0).sort((a,b)=>amountFor(b)-amountFor(a)).slice(0,6).map(a=><div className="dash-row" key={a.id}><span><i style={{color:categoryColors[a.category],background:categoryColors[a.category]+'20'}}>{a.symbol}</i>{a.category}</span><b>{a.name}</b><span><em className={`owner-chip ${a.owner==='夫'?'husband':a.owner==='妻'?'wife':'shared'}`}>{a.owner}</em></span><b>{yen(amountFor(a))}</b><span>{(amountFor(a)/total*100).toFixed(1)}%</span><b className={a.amount>=a.previous?'up':'down'}>{pct(a.amount,a.previous)}</b></div>)}</div></Card>
  </>;
}

function Assets({ assets, onAdd, onEdit, onDelete }: { assets:Asset[]; onAdd:(category?:Category)=>void; onEdit:(a:Asset)=>void; onDelete:(id:number)=>void }) {
  const [query,setQuery]=useState('');const [filter,setFilter]=useState<'すべて'|Category>('すべて');const [ownerFilter,setOwnerFilter]=useState('すべての所有者');const [scope,setScope]=useState<'全体'|'夫'|'妻'>('全体');
  const amountFor=(a:Asset)=>scope==='全体'?a.amount:ownerAmount(a,scope);const total=assets.reduce((s,a)=>s+amountFor(a),0);const categories=Object.keys(categoryColors) as Category[];
  const shown=assets.filter(a=>amountFor(a)>0&&(filter==='すべて'||a.category===filter)&&(ownerFilter==='すべての所有者'||a.owner===ownerFilter)&&a.name.toLowerCase().includes(query.toLowerCase()));
  return <><Header title="資産一覧" subtitle="資産種類ごとに残高と評価額を管理します" action={()=>onAdd()}/>
    <div className="asset-scope-switch">{(['全体','夫','妻'] as const).map(s=><button key={s} className={`${scope===s?'active ':''}${s==='夫'?'husband':s==='妻'?'wife':''}`} onClick={()=>setScope(s)}>{s}</button>)}</div>
    <div className="asset-scope-summary"><div><span>{scope==='全体'?'世帯全体':`${scope}の資産`}</span><b>{yen(total)}</b></div><small>{scope==='全体'?'登録資産を全額表示しています':`共有資産は${scope}の持分割合で按分しています`}</small></div>
    <div className="asset-category-summary">{categories.map(c=>{const items=assets.filter(a=>a.category===c&&amountFor(a)>0),sum=items.reduce((s,a)=>s+amountFor(a),0);return <button key={c} className={filter===c?'active':''} style={{'--cat':categoryColors[c]} as React.CSSProperties} onClick={()=>setFilter(c)}><i>{c==='預金'?'¥':c==='暗号資産'?'₿':c.charAt(0)}</i><span><small>{c}</small><b>{yen(sum)}</b><em>{items.length}件 · {scope}</em></span><strong onClick={e=>{e.stopPropagation();onAdd(c)}}><Icons.Plus/></strong></button>})}</div>
    <div className="asset-list-tabs"><button className={filter==='すべて'?'active':''} onClick={()=>setFilter('すべて')}>すべて</button>{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}<span>{assets.filter(a=>a.category===c&&amountFor(a)>0).length}</span></button>)}</div>
    <Card className="table-card categorized-table"><div className="toolbar"><div className="search"><Icons.Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="資産名で検索"/></div><select value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)}><option>すべての所有者</option><option>夫</option><option>妻</option><option>共有</option></select><button className="category-add" onClick={()=>onAdd(filter==='すべて'?undefined:filter)}><Icons.Plus/>{filter==='すべて'?'資産を追加':`${filter}を追加`}</button></div>
      {shown.length===0?<div className="empty-assets"><b>{scope}の{filter==='すべて'?'資産':filter}が登録されていません</b><button onClick={()=>onAdd(filter==='すべて'?undefined:filter)}><Icons.Plus/>追加する</button></div>:<div className="asset-table"><div className="tr th"><span>資産</span><span>所有者</span><span>カテゴリ</span><span>{scope}の評価額</span><span>前月比</span><span/></div>{shown.map(a=><div className="tr" key={a.id}><span className="asset-name"><i style={{color:categoryColors[a.category],background:categoryColors[a.category]+'18'}}>{a.symbol}</i><span><b>{a.name}</b><small>ID: {String(a.id).padStart(4,'0')}</small></span></span><span><em className={`owner-chip ${a.owner==='夫'?'husband':a.owner==='妻'?'wife':'shared'}`}>{a.owner}</em>{a.owner==='共有'&&<small className="share-label">夫{a.husbandShare}% / 妻{100-a.husbandShare}%</small>}</span><span><em className="category-dot" style={{background:categoryColors[a.category]}}/>{a.category}</span><b>{yen(amountFor(a))}</b><b className={a.amount>=a.previous?'up':'down'}>{pct(a.amount,a.previous)}</b><span className="row-actions"><button onClick={()=>onEdit(a)}><Icons.Pencil size={16}/></button><button onClick={()=>onDelete(a.id)}><Icons.Trash2 size={16}/></button></span></div>)}</div>}</Card>
    <div className="asset-total-strip"><span>表示中 {shown.length}件</span><b>合計 {yen(shown.reduce((s,a)=>s+amountFor(a),0))}</b><small>{scope}資産の {total?((shown.reduce((s,a)=>s+amountFor(a),0)/total)*100).toFixed(1):'0.0'}%</small></div>
  </>;
}

function History({records,onAdd}:{records:HistoryRecord[];onAdd:()=>void}) {
  const years=[...new Set(records.map(r=>r.month.slice(0,4)))].sort((a,b)=>b.localeCompare(a));const [year,setYear]=useState(years[0]||'2026');const shown=records.filter(r=>r.month.startsWith(year)).sort((a,b)=>a.month.localeCompare(b.month));const max=Math.max(...shown.map(r=>r.husband+r.wife),1);
  return <><Header title="推移・履歴" subtitle="世帯と夫婦それぞれの資産推移を比較します" action={onAdd}/><div className="history-legend"><span><i className="husband-bar"/>夫</span><span><i className="wife-bar"/>妻</span></div><Card className="history-chart"><div className="card-title"><div><h2>夫婦別 月間資産推移</h2><p>登録した月末時点の評価額</p></div><select className="period year-select" value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></div><div className="bars couple-bars">{shown.map((m,i)=><div className="bar-col" key={m.month}><div className="bar-value">{i===shown.length-1?`${((m.husband+m.wife)/1000000).toFixed(1)}M`:''}</div><div className="bar-pair"><div className="bar husband-bar" style={{height:`${m.husband/max*100}%`}}/><div className="bar wife-bar" style={{height:`${m.wife/max*100}%`}}/></div><span>{Number(m.month.slice(5))}月</span></div>)}</div></Card><Card className="history-table"><div className="card-title"><div><h2>月別パフォーマンス</h2><p>世帯全体の評価額と前月からの変化</p></div></div><div className="performance"><div className="perf-row head"><span>対象月</span><span>総資産額</span><span>増減額</span><span>増減率</span></div>{[...shown].reverse().map((m,i)=>{const current=m.husband+m.wife;const older=shown[shown.length-2-i];const previous=older?older.husband+older.wife:current;const diff=current-previous;return <div className="perf-row" key={m.month}><b>{m.month.replace('-','年')}月</b><b>{yen(current)}</b><span className={diff>=0?'up':'down'}>{diff>=0?'+':''}{yen(diff)}</span><span><em className={diff>=0?'badge positive':'badge negative'}>{pct(current,previous)}</em></span></div>})}</div></Card></>;
}

function HistoryModal({close,save}:{close:()=>void;save:(r:HistoryRecord)=>void}){const [month,setMonth]=useState('2026-08');const [husband,setHusband]=useState('');const [wife,setWife]=useState('');return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal history-modal"><button className="modal-close" onClick={close}><Icons.X size={20}/></button><span className="eyebrow">MONTHLY RECORD</span><h2>過去の資産を登録</h2><p>月末時点の夫婦それぞれの資産総額を入力します。同じ月を登録すると更新されます。</p><label>対象月<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="modal-columns"><label>夫の資産額<div className="money-input"><span>¥</span><input type="number" value={husband} onChange={e=>setHusband(e.target.value)} placeholder="0"/></div></label><label>妻の資産額<div className="money-input"><span>¥</span><input type="number" value={wife} onChange={e=>setWife(e.target.value)} placeholder="0"/></div></label></div><div className="record-total"><span>世帯合計</span><b>{yen(Number(husband)+Number(wife))}</b></div><div className="modal-actions"><button className="secondary" onClick={close}>キャンセル</button><button className="primary" disabled={!month||(!husband&&!wife)} onClick={()=>save({month,husband:Number(husband),wife:Number(wife)})}>履歴を保存</button></div></div></div>}

type AppSettings={lock:boolean;passcode:string;theme:'ダーク'|'ライト'|'システム';accent:string};

function SettingsView({settings,update,backup,restore}:{settings:AppSettings;update:(s:Partial<AppSettings>)=>void;backup:()=>void;restore:(f:File)=>void}) {
  const toggleLock=()=>{if(!settings.lock){const code=window.prompt('新しいパスコードを4桁以上で入力してください');if(!code||code.length<4)return;update({lock:true,passcode:code});}else{update({lock:false});}};
  const changePasscode=()=>{const code=window.prompt('新しいパスコードを4桁以上で入力してください');if(code&&code.length>=4)update({passcode:code,lock:true});};
  return <><Header title="設定" subtitle="セキュリティとアプリの表示を管理します"/><div className="settings-grid"><Card><div className="setting-heading"><span><Icons.Database size={20}/></span><div><h2>セキュリティ</h2><p>アプリとデータを保護します</p></div></div><div className="setting-row"><div><b>パスコードロック</b><small>起動時にパスコードを要求する</small></div><button className={`toggle ${settings.lock?'on':''}`} onClick={toggleLock}><i/></button></div><div className="setting-row"><div><b>パスコードを変更</b><small>{settings.passcode?'設定済み':'未設定'}</small></div><button className="secondary" onClick={changePasscode}>変更する</button></div></Card><Card><div className="setting-heading"><span><Icons.Download size={20}/></span><div><h2>バックアップと復元</h2><p>大切なデータを安全に保管します</p></div></div><div className="backup-actions"><button className="secondary" onClick={backup}><Icons.Download size={17}/>バックアップを作成</button><label className="secondary file-button"><Icons.Upload size={17}/>ファイルから復元<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label></div><div className="notice">資産と設定をJSONファイルとして、この端末へ保存します。</div></Card><Card className="wide"><div className="setting-heading"><span><Icons.Pencil size={20}/></span><div><h2>外観</h2><p>変更内容はすぐに適用・保存されます</p></div></div><div className="appearance"><div><b>テーマ</b><div className="segmented">{(['ダーク','ライト','システム'] as const).map(t=><button className={settings.theme===t?'selected':''} onClick={()=>update({theme:t})} key={t}>{t}</button>)}</div></div><div><b>アクセントカラー</b><div className="swatches">{['#35d6ba','#5c9dff','#8275ef','#c26fe8'].map(c=><button key={c} onClick={()=>update({accent:c})} className={settings.accent===c?'selected':''} style={{background:c}}/>)}</div></div></div></Card></div></>;
}

function AssetModal({ asset, close, save }: { asset:Asset|null|undefined; close:()=>void; save:(a:Omit<Asset,'id'>)=>void }) {
  const [name,setName]=useState(asset?.name??''); const [category,setCategory]=useState<Category>(asset?.category??'預金'); const [amount,setAmount]=useState(String(asset?.amount??'')); const [owner,setOwner]=useState<Owner>(asset?.owner??'夫'); const [husbandShare,setHusbandShare]=useState(asset?.husbandShare??50);
  const normalizedShare=owner==='夫'?100:owner==='妻'?0:husbandShare;
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="modal-close" onClick={close}><Icons.X size={20}/></button><span className="eyebrow">ASSET DETAILS</span><h2>{asset?'資産を編集':'新しい資産を追加'}</h2><p>所有者を指定すると、夫婦それぞれの資産額へ自動的に反映されます。</p><label>資産名<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="例：普通預金"/></label><div className="modal-columns"><label>カテゴリ<select value={category} onChange={e=>setCategory(e.target.value as Category)}>{Object.keys(categoryColors).map(c=><option key={c}>{c}</option>)}</select></label><label>所有者<select value={owner} onChange={e=>setOwner(e.target.value as Owner)}><option>夫</option><option>妻</option><option>共有</option></select></label></div>{owner==='共有'&&<div className="share-editor"><div><b>持分割合</b><span>夫 {husbandShare}%　/　妻 {100-husbandShare}%</span></div><input type="range" min="0" max="100" step="5" value={husbandShare} onChange={e=>setHusbandShare(Number(e.target.value))}/></div>}<label>現在の評価額<div className="money-input"><span>¥</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></div></label><div className="modal-actions"><button className="secondary" onClick={close}>キャンセル</button><button className="primary" disabled={!name||!amount} onClick={()=>save({name,category,amount:Number(amount),previous:asset?.previous??Number(amount),symbol:name.charAt(0).toUpperCase(),owner,husbandShare:normalizedShare})}>{asset?'変更を保存':'資産を追加'}</button></div></div></div>;
}

export default function App() {
  const [page,setPage]=useState<Page>('dashboard');
  const [assets,setAssetsState]=useState<Asset[]>(()=>{try{return JSON.parse(localStorage.getItem('aqua-assets')||'null')||initialAssets}catch{return initialAssets}});
  const [history,setHistoryState]=useState<HistoryRecord[]>(()=>{try{return JSON.parse(localStorage.getItem('aqua-history')||'null')||initialHistory}catch{return initialHistory}});
  const [cashflow,setCashflowState]=useState<CashflowItem[]>(()=>{try{return JSON.parse(localStorage.getItem('aqua-cashflow')||'null')||[{id:1,type:'income',name:'夫 給料',owner:'夫',amount:420000},{id:2,type:'income',name:'妻 給料',owner:'妻',amount:300000},{id:3,type:'expense',name:'住宅費',owner:'共有',amount:120000,day:1},{id:4,type:'expense',name:'水道・光熱費',owner:'共有',amount:18000,day:10},{id:5,type:'expense',name:'保険料',owner:'夫',amount:35000,day:15},{id:6,type:'expense',name:'通信費',owner:'共有',amount:8400,day:20},{id:7,type:'expense',name:'サブスク費用',owner:'妻',amount:5000,day:25}] as CashflowItem[]}catch{return[]}});
  const [settings,setSettingsState]=useState<AppSettings>(()=>{try{return JSON.parse(localStorage.getItem('aqua-settings')||'null')||{lock:false,passcode:'',theme:'ダーク',accent:'#35d6ba'}}catch{return{lock:false,passcode:'',theme:'ダーク',accent:'#35d6ba'}}});
  const [unlocked,setUnlocked]=useState(()=>!settings.lock||!settings.passcode); const [unlockCode,setUnlockCode]=useState(''); const [unlockError,setUnlockError]=useState(false);
  const [modal,setModal]=useState<Asset|null|undefined>(undefined); const [assetFlow,setAssetFlow]=useState<'categories'|Category|null>(null); const [historyModal,setHistoryModal]=useState(false); const [toast,setToast]=useState('');
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2600)};
  const setAssets=(value:Asset[]|((a:Asset[])=>Asset[]))=>setAssetsState(current=>{const next=typeof value==='function'?value(current):value;localStorage.setItem('aqua-assets',JSON.stringify(next));return next});
  const setHistory=(value:HistoryRecord[]|((a:HistoryRecord[])=>HistoryRecord[]))=>setHistoryState(current=>{const next=typeof value==='function'?value(current):value;localStorage.setItem('aqua-history',JSON.stringify(next));return next});
  const setCashflow=(value:(a:CashflowItem[])=>CashflowItem[])=>setCashflowState(current=>{const next=value(current);localStorage.setItem('aqua-cashflow',JSON.stringify(next));return next});
  const updateSettings=(part:Partial<AppSettings>)=>setSettingsState(current=>{const next={...current,...part};localStorage.setItem('aqua-settings',JSON.stringify(next));return next});
  const backup=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),assets,history,cashflow,settings},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`AquaAsset-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);notify('バックアップを作成しました')};
  const restore=async(file:File)=>{try{const data=JSON.parse(await file.text());if(!Array.isArray(data.assets))throw new Error();setAssets(data.assets);if(Array.isArray(data.history))setHistory(data.history);if(Array.isArray(data.cashflow))setCashflow(()=>data.cashflow);if(data.settings)updateSettings(data.settings);notify('バックアップを復元しました')}catch{window.alert('このファイルは有効なAquaAssetバックアップではありません。')}};
  const save=(data:Omit<Asset,'id'>)=>{const editing=Boolean(modal);setAssets(list=>modal ? list.map(a=>a.id===modal.id?{...data,id:a.id}:a) : [...list,{...data,id:Math.max(0,...list.map(a=>a.id))+1}]); setModal(undefined);notify(editing?'資産を更新しました':'資産を追加しました')};
  const saveCategoryAsset=(data:Omit<Asset,'id'>)=>{setAssets(list=>[...list,{...data,id:Math.max(0,...list.map(a=>a.id))+1}]);setAssetFlow(null);setPage('assets');notify('資産を追加しました')};
  const saveHistory=(record:HistoryRecord)=>{setHistory(list=>[...list.filter(r=>r.month!==record.month),record].sort((a,b)=>a.month.localeCompare(b.month)));setHistoryModal(false);notify('過去の資産データを保存しました')};
  const content=useMemo(()=>assetFlow==='categories'?<AssetCategoryView assets={assets} select={setAssetFlow} cancel={()=>setAssetFlow(null)}/>:assetFlow?<CategoryAssetForm category={assetFlow} cancel={()=>setAssetFlow('categories')} save={saveCategoryAsset}/>:page==='dashboard'?<Dashboard assets={assets} records={history} add={()=>setAssetFlow('categories')} showAssets={()=>setPage('assets')}/>:page==='assets'?<Assets assets={assets} onAdd={category=>setAssetFlow(category??'categories')} onEdit={setModal} onDelete={id=>{setAssets(a=>a.filter(x=>x.id!==id));notify('資産を削除しました')}}/>:page==='income'?<IncomeView items={cashflow} setItems={setCashflow}/>:page==='history'?<History records={history} onAdd={()=>setHistoryModal(true)}/>:<SettingsView settings={settings} update={part=>{updateSettings(part);notify('設定を保存しました')}} backup={backup} restore={restore}/>,[page,assets,history,cashflow,settings,assetFlow]);
  const themeClass=settings.theme==='ライト'?'theme-light':settings.theme==='システム'?'theme-system':'theme-dark';
  if(!unlocked)return <div className={`lock-screen ${themeClass}`} style={{'--accent':settings.accent} as React.CSSProperties}><div className="lock-card"><div className="lock-logo">A</div><span className="eyebrow">AQUAASSET</span><h1>おかえりなさい</h1><p>資産情報を表示するにはパスコードを入力してください。</p><input autoFocus type="password" inputMode="numeric" value={unlockCode} onChange={e=>{setUnlockCode(e.target.value);setUnlockError(false)}} onKeyDown={e=>{if(e.key==='Enter'){if(unlockCode===settings.passcode)setUnlocked(true);else setUnlockError(true)}}} placeholder="パスコード"/><button className="primary" onClick={()=>{if(unlockCode===settings.passcode)setUnlocked(true);else setUnlockError(true)}}>ロックを解除</button>{unlockError&&<small>パスコードが違います</small>}</div></div>;
  return <div className={`app ${themeClass}`} style={{'--accent':settings.accent} as React.CSSProperties}><Sidebar page={page} setPage={p=>{setAssetFlow(null);setPage(p)}}/><main><div className="page-enter" key={`${page}-${assetFlow??''}`}>{content}</div></main>{modal!==undefined&&<AssetModal asset={modal} close={()=>setModal(undefined)} save={save}/>} {historyModal&&<HistoryModal close={()=>setHistoryModal(false)} save={saveHistory}/>} {toast&&<div className="toast"><span>✓</span>{toast}</div>}</div>;
}
