import { useState } from 'react';
import type React from 'react';
import { Banknote, Bitcoin, CandlestickChart, ChevronLeft, ChevronRight, CirclePlus, Globe2, Landmark, MoreHorizontal, PieChart, Plus, ReceiptText, Trash2, TrendingUp, UsersRound, WalletCards, X } from 'lucide-react';
import { Card, Header } from './components';
import { yen } from './data';
import type { Asset, CashflowItem, Category, Owner } from './types';

const categoryMeta:Record<Category,{title:string;description:string;color:string;icon:typeof Landmark}>={
  '預金':{title:'預金・現金',description:'銀行口座の預金や手元の現金',color:'#35d6ba',icon:Landmark},
  '国内株式':{title:'国内株式',description:'日本の上場企業の株式',color:'#5798ff',icon:CandlestickChart},
  '米国株式':{title:'米国株式',description:'米国株式やETF',color:'#2bbef2',icon:Globe2},
  '投資信託':{title:'投資信託',description:'投資信託やファンド',color:'#b76aff',icon:PieChart},
  '暗号資産':{title:'暗号資産',description:'Bitcoinなどの暗号資産',color:'#f3a53f',icon:Bitcoin},
  'その他':{title:'その他の資産',description:'債券や金などその他の資産',color:'#94a3b8',icon:CirclePlus},
};

export function AssetCategoryView({assets,select,cancel}:{assets:Asset[];select:(c:Category)=>void;cancel:()=>void}){
  return <><Header title="資産を追加" subtitle="登録する資産の種類を選択してください"/><div className="category-grid">{(Object.keys(categoryMeta) as Category[]).map(c=>{const m=categoryMeta[c],Icon=m.icon;return <button className="category-card" style={{'--cat':m.color} as React.CSSProperties} key={c} onClick={()=>select(c)}><span className="category-icon"><Icon/></span><span><b>{m.title}</b><small>{m.description}<br/>を登録します</small></span><ChevronRight/></button>})}</div><Card className="recent-assets"><div className="card-title"><div><h2>最近追加した資産</h2><p>直近に登録した資産</p></div></div>{[...assets].slice(-3).reverse().map(a=>{const m=categoryMeta[a.category],Icon=m.icon;return <div className="recent-row" key={a.id}><i style={{color:m.color,background:m.color+'18'}}><Icon/></i><b>{a.name}</b><span>{m.title}</span><small>{a.owner}</small><strong>{yen(a.amount)}</strong></div>})}</Card><button className="back-button" onClick={cancel}><ChevronLeft/>資産一覧へ戻る</button></>;
}

export function CategoryAssetForm({category,cancel,save}:{category:Category;cancel:()=>void;save:(a:Omit<Asset,'id'>)=>void}){
  const meta=categoryMeta[category],Icon=meta.icon;const [name,setName]=useState('');const [institution,setInstitution]=useState('');const [code,setCode]=useState('');const [owner,setOwner]=useState<Owner>('夫');const [quantity,setQuantity]=useState('');const [price,setPrice]=useState('');const [amount,setAmount]=useState('');const [share,setShare]=useState(50);
  const calculated=category==='預金'||category==='その他'?Number(amount):Number(quantity)*Number(price);const canSave=name&&calculated>0;
  const labels=category==='暗号資産'?{name:'通貨名',code:'シンボル',institution:'取引所',quantity:'保有数量',price:'現在価格'}:category==='投資信託'?{name:'ファンド名',code:'商品コード',institution:'証券会社',quantity:'保有口数',price:'現在の基準価額'}:{name:'銘柄名',code:'証券コード',institution:'証券会社',quantity:'保有数量',price:'現在値'};
  return <><Header title={`${meta.title}を登録`} subtitle="資産種類　›　詳細入力　›　確認"/><div className="asset-form-layout"><Card className="category-form"><div className="form-accent" style={{background:meta.color}}/><label>{category==='預金'?'金融機関・口座名':labels.name}<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={category==='預金'?'例：住信SBIネット銀行':category==='国内株式'?'例：トヨタ自動車':''}/></label>{category!=='預金'&&category!=='その他'&&<div className="form-columns"><label>{labels.code}<input value={code} onChange={e=>setCode(e.target.value)} placeholder={category==='国内株式'?'7203':''}/></label><label>{labels.institution}<input value={institution} onChange={e=>setInstitution(e.target.value)} placeholder="例：SBI証券"/></label></div>}<label>保有者<div className="owner-segment">{(['夫','妻','共有'] as Owner[]).map(o=><button className={owner===o?'active':''} onClick={()=>setOwner(o)} key={o}>{o}</button>)}</div></label>{owner==='共有'&&<div className="share-box"><span>夫 {share}%</span><input type="range" min="0" max="100" step="5" value={share} onChange={e=>setShare(Number(e.target.value))}/><span>妻 {100-share}%</span></div>}{category==='預金'||category==='その他'?<label>現在の評価額<div className="amount-field"><span>¥</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></div></label>:<div className="form-columns"><label>{labels.quantity}<input type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="0"/></label><label>{labels.price}<div className="amount-field"><span>¥</span><input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0"/></div></label></div>}<label>評価額<div className="calculated-value">{yen(calculated)}<small>入力内容から自動計算</small></div></label></Card><Card className="form-preview"><h2>登録内容</h2><div className="preview-title"><i style={{color:meta.color,background:meta.color+'18'}}><Icon/></i><div><b>{name||meta.title}</b><small>{code||meta.title}</small></div></div><hr/><span>評価額</span><strong style={{color:meta.color}}>{yen(calculated)}</strong><hr/><span>保有者</span><b>{owner}{owner==='共有'?`（夫${share}%・妻${100-share}%）`:''}</b><div className="preview-ring" style={{background:`conic-gradient(${meta.color} 0 ${owner==='妻'?0:owner==='夫'?100:share}%,#a855f7 ${owner==='妻'?0:owner==='夫'?100:share}% 100%)`}}><i/></div></Card></div><div className="form-actions"><button className="secondary" onClick={cancel}>キャンセル</button><button className="primary" disabled={!canSave} onClick={()=>save({name,category,amount:calculated,previous:calculated,symbol:category==='暗号資産'?'₿':name.charAt(0).toUpperCase(),owner,husbandShare:owner==='夫'?100:owner==='妻'?0:share})}>{meta.title}を登録</button></div></>;
}

function CashflowModal({type,close,save}:{type:'income'|'expense';close:()=>void;save:(i:Omit<CashflowItem,'id'>)=>void}){const [name,setName]=useState('');const [owner,setOwner]=useState<Owner>('夫');const [amount,setAmount]=useState('');const [day,setDay]=useState('1');return <div className="modal-backdrop"><div className="modal cash-modal"><button className="modal-close" onClick={close}><X/></button><span className="eyebrow">{type==='income'?'INCOME':'FIXED COST'}</span><h2>{type==='income'?'収入を追加':'固定費を追加'}</h2><label>項目名<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={type==='income'?'例：夫 給料':'例：住宅費'}/></label><label>所有者<select value={owner} onChange={e=>setOwner(e.target.value as Owner)}><option>夫</option><option>妻</option><option>共有</option></select></label><label>月額<div className="money-input"><span>¥</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></div></label>{type==='expense'&&<label>支払日<input type="number" min="1" max="31" value={day} onChange={e=>setDay(e.target.value)}/></label>}<div className="modal-actions"><button className="secondary" onClick={close}>キャンセル</button><button className="primary" disabled={!name||!amount} onClick={()=>save({type,name,owner,amount:Number(amount),day:type==='expense'?Number(day):undefined})}>追加する</button></div></div></div>}

export function IncomeView({items,setItems}:{items:CashflowItem[];setItems:(f:(x:CashflowItem[])=>CashflowItem[])=>void}){const [modal,setModal]=useState<'income'|'expense'|null>(null);const income=items.filter(i=>i.type==='income'),expenses=items.filter(i=>i.type==='expense'),incomeTotal=income.reduce((s,i)=>s+i.amount,0),expenseTotal=expenses.reduce((s,i)=>s+i.amount,0),surplus=incomeTotal-expenseTotal;const add=(item:Omit<CashflowItem,'id'>)=>{setItems(x=>[...x,{...item,id:Math.max(0,...x.map(i=>i.id))+1}]);setModal(null)};const remove=(id:number)=>setItems(x=>x.filter(i=>i.id!==id));return <><Header title="収支管理" subtitle="夫婦の給料と毎月の固定費を管理します"/><div className="cash-summary"><Card><i><UsersRound/></i><span>世帯手取り</span><b>{yen(incomeTotal)}</b></Card><Card><i><ReceiptText/></i><span>固定費</span><b>{yen(expenseTotal)}</b></Card><Card><i><TrendingUp/></i><span>毎月の余力</span><b>{yen(surplus)}</b></Card></div><div className="cash-columns"><Card><div className="cash-title"><h2>給料・収入</h2><button onClick={()=>setModal('income')}><Plus/>収入を追加</button></div>{income.map(i=><div className="cash-row" key={i.id}><i><Banknote/></i><span><b>{i.name}</b><small>{i.owner}</small></span><strong>{yen(i.amount)}</strong><button onClick={()=>remove(i.id)}><Trash2/></button></div>)}</Card><Card><div className="cash-title"><h2>固定費</h2><button onClick={()=>setModal('expense')}><Plus/>固定費を追加</button></div>{expenses.map(i=><div className="cash-row" key={i.id}><i><WalletCards/></i><span><b>{i.name}</b><small>{i.owner} · 毎月{i.day}日</small></span><strong>{yen(i.amount)}</strong><button onClick={()=>remove(i.id)}><Trash2/></button></div>)}</Card></div><Card className="savings-card"><div><h2>収入と固定費の内訳</h2><div className="income-bar"><i style={{width:`${incomeTotal?surplus/incomeTotal*100:0}%`}}/><span/></div><small>世帯手取り {yen(incomeTotal)}</small><small>固定費 {yen(expenseTotal)}</small></div><div><span>貯蓄率</span><b>{incomeTotal?(surplus/incomeTotal*100).toFixed(1):'0.0'}%</b><small>毎月の余力 {yen(surplus)}</small></div></Card>{modal&&<CashflowModal type={modal} close={()=>setModal(null)} save={add}/>}</>}
